-- MySQL Script generated by MySQL Workbench
-- 10/18/14 23:06:48
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SELIA_RSM
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema selia_pos
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Selia_Control
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `DEPARTMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEPARTMENTS` (
  `department_id` INT NOT NULL AUTO_INCREMENT COMMENT 'INVENTORY, NON INVENTORY, SERVICE,',
  `department` VARCHAR(45) NULL,
  PRIMARY KEY (`department_id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 0;


-- -----------------------------------------------------
-- Table `ITEMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ITEMS` (
  `item_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `item` VARCHAR(45) NOT NULL,
  `dim_id_1` INT NULL DEFAULT NULL,
  `dim_id_2` INT NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `ITEM_UNIQUE` (`item` ASC, `dim_id_1` ASC, `dim_id_2` ASC))
  ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CATALOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CATALOG` (
  `catalog_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT(10) NOT NULL,
  `SKU` VARCHAR(20) NULL,
  `attribute_id_1` INT NULL,
  `attribute_id_2` INT NULL DEFAULT NULL,
  `description` VARCHAR(500) NULL,
  `unit_cost` DECIMAL(10,2) NULL DEFAULT 0.00,
  `margin` DECIMAL(10,0) NULL,
  `taxable` INT(1) NULL,
  `sell_price` DECIMAL(10,2) NULL DEFAULT 0.00,
  `must_input_price` INT(1) NULL DEFAULT 0,
  `do_not_discount` INT(1) NULL DEFAULT 0,
  `capture_serial` INT(1) NULL,
  `UPC` VARCHAR(13) NULL DEFAULT NULL,
  `active` INT(1) NULL DEFAULT 1,
  PRIMARY KEY (`catalog_id`),
  UNIQUE INDEX `item_ITEM_ID_UNIQUE` (`item_id` ASC, `attribute_id_1` ASC, `attribute_id_2` ASC)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1;
-- -----------------------------------------------------
-- Table `DIMENSIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DIMENSIONS` (
  `dimension_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dimension` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dimension_id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 56
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ATTRIBUTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATTRIBUTES` (
  `attribute_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dimension_id` INT(10) UNSIGNED NOT NULL,
  `attribute` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`attribute_id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 662
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TAXES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TAXES` (
  `tax_id` INT NOT NULL AUTO_INCREMENT,
  `tax_description` VARCHAR(45) NULL,
  `tax_prc` DOUBLE NULL,
  PRIMARY KEY (`tax_id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STORES` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `store_type` INT(1) NULL COMMENT '1 -> Main store' /* comment truncated */ /*2 -> store*/,
  `store_name` VARCHAR(45) NULL,
  `add1` VARCHAR(45) NULL,
  `add2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` INT NULL,
  PRIMARY KEY (`store_id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STORE_TAXES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STORE_TAXES` (
  `STORE_TAXES_ID` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NOT NULL,
  `tax_id` INT NOT NULL,
  PRIMARY KEY (`STORE_TAXES_ID`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INVENTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INVENTORY` (
  `INVENTORY_ID` INT NOT NULL,
  `store_id` INT NOT NULL,
  `catalog_id` INT(10) UNSIGNED NOT NULL,
  `current_count` FLOAT NULL,
  PRIMARY KEY (`INVENTORY_ID`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INVOICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INVOICE` (
  `store_id` INT,
  `inv_type` INT(1),
  `inv_num` INT(11),
  `rcpt_media` VARCHAR(3) NULL,
  `email` VARCHAR(100) NULL,
  `cell_num` VARCHAR(15) NULL,
  `ts` TIMESTAMP,
  `employee_id` INT
);
-- -----------------------------------------------------
-- Table `TRNS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TRNS` (
  `store_id` INT NOT NULL,
  `inv_num` INT(11) NOT NULL,
  `inv_type` INT(1) NOT NULL,
  `TransCode` VARCHAR(2),
  `SEQ` INT(10),
  `SKU` INT(10),
  `sell_price` DOUBLE NULL,
  `qty` DOUBLE,
  `taxable` INT,
  `sub_total` DOUBLE NULL,
  `reason_id` INT NULL DEFAULT NULL,
  `serial_number` VARCHAR(45) NULL
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;